### https://towardsdatascience.com/another-twitter-sentiment-analysis-with-python-part-2-333514854913

#### In order for me to implement a couple of data visualisation in the next step, I need term frequency data. What kind of words are used in the tweets, and how many times it is used in entire corpus. I used count vectorizer to calculate the term frequencies, even though the count vectorizer is also for fit, train and predict, but at this stage, I will just be extracting the term frequencies for the visualisation.

#### There are parameter options available for count vectorizer, such as removing stop words, limiting the maximum number of terms. However, in order to get a full picture of the dataset first, I implemented with stop words included, and not limiting the maximum number of terms.

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from nltk.tokenize import WordPunctTokenizer
from bs4 import BeautifulSoup
import re

csv ='./03_result/clean_tweet_updated1.csv'
my_df = pd.read_csv(csv,index_col = 0)
my_df.head()
my_df.dropna(inplace=True)
my_df.reset_index(drop=True,inplace=True)

my_df.count()

text      798153
target    798153
dtype: int64

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cvec = CountVectorizer()
cvec.fit(my_df.text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [5]:
len(cvec.get_feature_names())

160423

In [6]:
neg_doc_matrix = cvec.transform(my_df[my_df.target == 0].text)
pos_doc_matrix = cvec.transform(my_df[my_df.target == 1].text)
neg_tf = np.sum(neg_doc_matrix,axis=0)
pos_tf = np.sum(pos_doc_matrix,axis=0)
neg = np.squeeze(np.asarray(neg_tf))
pos = np.squeeze(np.asarray(pos_tf))
term_freq_df = pd.DataFrame([neg,pos],columns=cvec.get_feature_names()).transpose()

In [7]:
term_freq_df

                                                      0  1
aa                                                  159  0
aaa                                                  93  0
aaaa                                                 45  0
aaaaa                                                26  0
aaaaaa                                               16  0
aaaaaaa                                               9  0
aaaaaaaa                                             13  0
aaaaaaaaa                                             6  0
aaaaaaaaaa                                            6  0
aaaaaaaaaaa                                           4  0
aaaaaaaaaaaa                                          3  0
aaaaaaaaaaaaa                                         6  0
aaaaaaaaaaaaaa                                        1  0
aaaaaaaaaaaaaaaa                                      1  0
aaaaaaaaaaaaaaaaaa                                    2  0
aaaaaaaaaaaaaaaaaaaa                                  1  0
aaaaaaaaaaaaaaaaaaaaaaa                               1  0
aaaaaaaaaaaaaaaaaaaaaaaaaa                            1  0
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa                     1  0
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa     1  0
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaah             1  0
aaaaaaaaaaaaaaaaaaaaaaaaaaaaall                       1  0
aaaaaaaaaaaaaaaaaaaaaaaaaaaao                         1  0
aaaaaaaaaaaaaaaaaaaaaaaaaargh                         1  0
aaaaaaaaaaaaaaaaaaaaaaahhhhhhhhhhhhhhhhhhhhhhhh...    1  0
aaaaaaaaaaaaaaaaaaaaaaahrg                            1  0
aaaaaaaaaaaaaaaaaaaaahhhhh                            1  0
aaaaaaaaaaaaaaaaaaaah                                 1  0
aaaaaaaaaaaaaaaaaaaay                                 1  0
aaaaaaaaaaaaaaaaaah                                   1  0
...                                                 ... ..
zzzz                                                 53  0
zzzzland                                              1  0
zzzzness                                              1  0
zzzzs                                                 3  0
zzzzy                                                 1  0
zzzzz                                                44  0
zzzzzs                                                2  0
zzzzzz                                               30  0
zzzzzzz                                              14  0
zzzzzzzz                                             12  0
zzzzzzzzlullaby                                       1  0
zzzzzzzzz                                            12  0
zzzzzzzzzz                                            8  0
zzzzzzzzzzz                                          12  0
zzzzzzzzzzzz                                          3  0
zzzzzzzzzzzzz                                         4  0
zzzzzzzzzzzzzz                                        3  0
zzzzzzzzzzzzzzz                                       3  0
zzzzzzzzzzzzzzzz                                      3  0
zzzzzzzzzzzzzzzzs                                     1  0
zzzzzzzzzzzzzzzzz                                     2  0
zzzzzzzzzzzzzzzzzz                                    2  0
zzzzzzzzzzzzzzzzzzz                                   2  0
zzzzzzzzzzzzzzzzzzzz                                  1  0
zzzzzzzzzzzzzzzzzzzzz                                 1  0
zzzzzzzzzzzzzzzzzzzzzz                                1  0
zzzzzzzzzzzzzzzzzzzzzzz                               1  0
zzzzzzzzzzzzzzzzzzzzzzzzzzz                           1  0
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...    1  0
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...    1  0

[160423 rows x 2 columns]

In [8]:
document_matrix = cvec.transform(my_df.text)
my_df[my_df.target == 0].tail()

                                                     text  target
798148    sick spending my day laying in bed listening to       0
798149                                      gmail is down       0
798150                        rest in peace farrah so sad       0
798151  sounds like rival is flagging your ads not muc...       0
798152  has to resit exams over summer wishes he worke...       0